FROM docker.io/library/debian:13

# Remove container-specific APT configurations, and install required packages
RUN rm /etc/apt/apt.conf.d/docker-* && \
    apt-get update && \
    apt-get install -y \
        bash-completion \
        bzip2 \
        curl \
        git \
        gnupg \
        htop \
        less \
        locales \
        man-db \
        manpages \
        nano \
        openssh-client \
        openssh-server \
        procps \
        sudo \
        tini \
        trash-cli \
        tree \
        vim \
        wget \
        zip \
        && \
    apt-get clean && \
    rm -dr /var/lib/apt/lists/*

# Configure locale with UTF-8 support
RUN update-locale LANG=C.UTF-8 LC_ALL=C.UTF-8

# Configure SSH server
RUN echo "StreamLocalBindUnlink yes" >> /etc/ssh/sshd_config && \
    echo "AuthorizedKeysFile /etc/ssh/authorized_keys" >> /etc/ssh/sshd_config && \
    touch /etc/ssh/authorized_keys

# Set up the init and stop
RUN mkdir -p /etc/dbx
COPY init stop /sbin
ENTRYPOINT ["/sbin/init"]
