#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 Nicholas Rodrigues Lordello <n@lordello.net>

if [ "$(id -u)" -ne 0 ]; then
	printf '%s: operation not permitted\n' "$0" >&2
	exit 1
fi

touch /run/.dbxenv
printf "%d\n" "$$" >/run/dbx.pid

if [ -f /etc/dbx/init.local ] && [ -x /etc/dbx/init.local ]; then
	/etc/dbx/init.local ||
		printf '%s: init.local failed (%d)\n' "$0" "$?" >&2
fi

# The init process is not guaranteed to be on PID 1 for all runtimes (notably,
# `krun` will wrap the init process). Tell tini to act like an init process
# regardless of its PID.
export TINI_SUBREAPER=yes

exec /usr/bin/tini /usr/sbin/sshd -- -D -e
