#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 Nicholas Rodrigues Lordello <n@lordello.net>

if [ ! -f /run/.dbxenv ]; then
	echo "ERROR: not in a devbox" >&2
	exit 1
fi

exec /usr/bin/tini /usr/sbin/sshd -- -D -e
