#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

r="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

usage() {
    cat <<EOF
dbx - containerized development environments

USAGE:
    dbx create              creates a devbox if one does not already exist
    dbx [enter]             enters the devbox in the current directory
    dbx link CMD            creates a host link to a devbox command
    dbx proxy PORT          proxies a container port to the host
    dbx run CMD [ARGS...]   runs a command within the devbox
EOF
}

cmd="${1:-enter}"
shift || true

case "$#:$cmd" in
    0:create|0:enter|1:link|1:proxy|[1-9]:run|[1-9][0-9]:run)
        "$r/dbx-$cmd" "$@"
        ;;
    *)
        usage
        exit 1
        ;;
esac
