#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 Nicholas Rodrigues Lordello <n@lordello.net>

set -euo pipefail

command=enter
name="dbx"
image=ghcr.io/nlordell/dbx:latest
port=4222
script=
asroot=
autostart=
fileonly=
regenerate=
args=()

OS="$(uname -s)"
DATADIR="${XDG_DATA_HOME:-$HOME/.local/share}/dbx"
CONFIGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/dbx"

usage() {
	cat <<USAGE
usage: $0 [COMMAND] [OPTIONS...] [ARGS...]
commands:
    cp          copies files to and from a devbox
    create      create a new devbox
    enter       opens a shell in a devbox (default: \`dbx enter -s\`)
    exec        executes a command in a devbox
    proxy       proxies a devbox port to the host
    ssh         print devbox \`ssh\` connection flags
    start       starts a devbox
    stop        stops a devbox
options:
    -n NAME     name of the devbox container (default: $name)
create options:
    -i IMAGE    devbox container image (default: $image)
    -p PORT     host port \`sshd\` binds to (default: $port)
    -x SCRIPT   post installation script
cp/enter/exec options:
    -R          connect as root instead of the development user
    -s          start the devbox if necessary
ssh options:
    -F          only print the path to the \`ssh_config\` file
    -g          re-generate the SSH configuration
cp arguments:
    SOURCE...   one or more source files to copy from
    TARGET      the target to copy to
exec arguments:
    COMMAND...  command and arguments to execute
proxy arguments:
    PORT[:HOST] the devbox port to proxy on the host; optionally
                specify an alternate host port to bind to
USAGE
	exit 0
}

version() {
	printf "0.0.1\n"
	exit 0
}

has_commands() {
	local cmd

	for cmd in "$@"; do
		if ! command -v "$cmd" &>/dev/null; then
			return 1
		fi
	done
	return 0
}

perror() {
	local code="$1"
	local msg="$2"

	printf "%s: %s\n" "$0" "$msg" >&2
	exit "$code"
}

general_error() { perror 1 "$1"; }
usage_error() { perror 1 "$1"; }

parse_name() {
	local name="$1"

	# Restrict allowed names only lower case letters and digits, with hyphens
	# only allowed in the middle of the name. This is restrictive, but matches
	# what is allowed by `container machine`.
	case "$name" in
	"" | [!a-z0-9]* | *[!a-z0-9-]* | *[!a-z0-9])
		usage_error "invalid devbox name '$name'"
		;;
	esac
	printf "%s\n" "$name"
}

parse_image() {
	local image="$1"

	# Make sure that the image isn't an option passed to the engine.
	case "$image" in
	"" | -*)
		usage_error "invalid image '$image'"
		;;
	esac
	printf "%s\n" "$image"
}

parse_port() {
	local port="$1"

	if ! {
		[ "$port" -ge 1 ] && [ "$port" -le 65535 ]
	} 2>/dev/null; then
		usage_error "invalid port '$port'"
	fi
	printf "%s\n" "$port"
}

parse_file() {
	local file="$1"

	if ! [ -f "$file" ] || ! [ -r "$file" ]; then
		usage_error "cannot read '$file'"
	fi
	printf "%s\n" "$file"
}

parse_opt() {
	local opt="$1"
	local arg="$2"

	case "$opt" in
	h) usage ;;
	v) version ;;
	n) name="$(parse_name "$arg")" ;;
	i) image="$(parse_image "$arg")" ;;
	p) port="$(parse_port "$arg")" ;;
	x) script="$(parse_file "$arg")" ;;
	R) asroot=t ;;
	s) autostart=t ;;
	F) fileonly=t ;;
	g) regenerate=t ;;
	:) usage_error "missing argument for -$arg" ;;
	\?) usage_error "invalid option -$arg" ;;
	esac
}

parse_opts() {
	local optstr=":hvn:"

	if [ -n "${DBX_NAME:-}" ]; then
		name="$(parse_name "$DBX_NAME")"
	fi

	OPTIND=1
	while getopts "$optstr" opt; do
		parse_opt "$opt" "${OPTARG:-?}"
	done
	shift $((OPTIND - 1))

	if [ $# -gt 0 ]; then
		command="$1"
		shift
	else
		autostart=t
	fi

	case "$command" in
	create) optstr="${optstr}i:p:x:" ;;
	cp | enter | exec) optstr="${optstr}Rs" ;;
	ssh) optstr="${optstr}Fg" ;;
	proxy | start | stop) ;;
	*) usage_error "unknown command '$command'" ;;
	esac

	OPTIND=1
	while getopts "$optstr" opt; do
		parse_opt "$opt" "${OPTARG:-?}"
	done
	shift $((OPTIND - 1))

	case "$command" in
	cp)
		case "$#" in
		0) usage_error "missing argument 'SOURCE'" ;;
		1) usage_error "missing argument 'TARGET'" ;;
		esac

		# We want to make sure that there are no `host:...` paths that are not
		# for the devbox, and make `:...` paths short-hand for remote paths.
		for f in "$@"; do
			case "$f" in
			"$name":*) ;;
			:*) f="$name$f" ;;
			*:*) usage_error "invalid path specifier '$f'" ;;
			esac
			args+=("$f")
		done
		shift $#
		;;
	exec)
		case "$#" in
		0) usage_error "missing argument 'COMMAND'" ;;
		esac

		args=("$@")
		shift $#
		;;
	proxy)
		case "$#" in
		0) usage_error "missing argument 'PORT'" ;;
		esac

		args=("$(parse_port "${1%%:*}")")
		case "$1" in
		*:*) args+=("$(parse_port "${1#*:}")") ;;
		*) args+=("${args[0]}") ;;
		esac
		shift
		;;
	esac

	if [ $# -gt 0 ]; then
		usage_error "unexpected argument '$1'"
	fi
}

ssh_id() {
	printf "%s\n" "$DATADIR/$name.id_ed25519"
}

ssh_config() {
	printf "%s\n" "$DATADIR/$name.ssh_config"
}

ssh_user() {
	local user

	if [ -n "$asroot" ]; then
		user="root"
	else
		user="%u"
	fi
	printf "User=%s\n" "$user"
}

ssh_knownhosts() {
	printf "%s\n" "$DATADIR/$name.known_hosts"
}

ssh_init() {
	mkdir -p "$DATADIR" "$CONFIGDIR"
	rm -f "$(ssh_id)" "$(ssh_id).pub" "$(ssh_knownhosts)"
	ssh-keygen -C dbx -f "$(ssh_id)" -N "" -t ed25519 \
		</dev/null >/dev/null 2>/dev/null
}

ssh_configure() {
	local hostname
	local port
	local userconfig="$CONFIGDIR/$name.ssh_config"

	hostname="$(engine_hostname)"
	port="$(engine_port)"
	cat <<SSH_CONFIG >"$(ssh_config)"
Host $name
	Hostname $hostname
	Port $port
	BatchMode yes
	ConnectTimeout 1
	IdentitiesOnly yes
	IdentityFile "$(ssh_id)"
	PreferredAuthentications publickey
	StrictHostKeyChecking accept-new
	UserKnownHostsFile "$(ssh_knownhosts)"
	Include "$userconfig"
SSH_CONFIG
}

cmd_cp() {
	(cmd_exec exit)
	exec scp -F "$(ssh_config)" -o "$(ssh_user)" -- "$@"
}

cmd_create() {
	if engine_iscreated; then
		general_error "devbox name in use"
	fi

	ssh_init
	engine_create

	if [ -n "$script" ]; then
		cmd_start
		scp -q -F "$(ssh_config)" -- "$script" "$name:/tmp/post-install"
		ssh -q -F "$(ssh_config)" "$name" \
			"chmod +x /tmp/post-install && /tmp/post-install"
		engine_stop
	fi
}

cmd_enter() {
	cmd_exec
}

cmd_exec() {
	if [ -n "$autostart" ]; then
		cmd_start
	elif ! engine_isrunning; then
		general_error 'devbox is not started'
	fi
	exec ssh -q -F "$(ssh_config)" -o "$(ssh_user)" "$name" -- "$@"
}

cmd_proxy() {
	local devboxport="$1"
	local hostport="$2"

	if ! engine_isrunning; then
		general_error 'devbox is not started'
	fi

	exec ssh -q -F "$(ssh_config)" \
		-o "ExitOnForwardFailure=yes" \
		-L "localhost:$hostport:localhost:$devboxport" -N \
		"$name"
}

cmd_ssh() {
	if ! engine_iscreated || [ ! -f "$(ssh_id)" ]; then
		general_error "devbox not created"
	fi

	if [ -n "$regenerate" ]; then
		ssh_configure
	fi

	if [ -n "$fileonly" ]; then
		ssh_config
	else
		printf "-F '%s' %s\n" "$(ssh_config)" "$name"
	fi
}

cmd_start() {
	if engine_isrunning; then
		return 0
	fi

	engine_start
	ssh_configure
	engine_waitforsshd
}

cmd_stop() {
	engine_stop
}

if [ "$OS" = "Darwin" ] && has_commands container; then
	engine_init() {
		if ! container system status &>/dev/null; then
			general_error "container engine not running"
		fi
	}

	engine_create() {
		# The container engine does not bind to a host port with `sshd`, and so
		# it ignores the option.
		: "$port"

		container machine create \
			--name="$name" \
			--no-boot \
			--home-mount=none \
			"$image"

		# Provision the devbox. Note that there is no way to access the
		# filesystem on the container machine directly, so use the script
		# to authorise our SSH key. Additionally, remove the automatically
		# given `sudo` access from the devbox user; the expectation is to
		# use `dbx (exec|enter) -r` to perform priviledged operations.
		container machine run \
			--name="$name" \
			--root \
			"
				printf '%s\n' '$(cat "$(ssh_id).pub")' > /etc/ssh/authorized_keys
				rm '/etc/sudoers.d/$(id -un | tr . _)'
			"
		engine_stop
	}

	engine_start() {
		# The only way to start a machine is to run a command - use one that
		# does nothing but return a `0` exit code.
		container machine run \
			--name="$name" \
			--root \
			true
	}

	engine_waitforsshd() {
		:
	}

	engine_stop() {
		container machine stop "$name" >/dev/null
	}

	engine_iscreated() {
		container machine inspect "$name" &>/dev/null
	}

	engine_isrunning() {
		local status

		status="$(
			container machine inspect "$name" 2>/dev/null |
				grep '"status"' |
				cut -d'"' -f4
		)"
		[ "$status" = "running" ]
	}

	engine_hostname() {
		local ipaddress

		ipaddress="$(
			container machine inspect "$name" |
				grep '"ipAddress"' |
				cut -d'"' -f4
		)"
		if [ -z "$ipaddress" ]; then
			general_error "failed to read devbox IP address"
		fi
		printf "%s\n" "$ipaddress"
	}

	engine_port() {
		printf "22\n"
	}
elif [ "$OS" = "Linux" ] && has_commands podman krun; then
	krun_vmconfig() {
		printf "%s\n" "$CONFIGDIR/$name.krun_vm.json"
	}

	engine_init() {
		if [ "$(id -u)" -eq 0 ]; then
			general_error "krun runtime insecure as root"
		fi
	}

	engine_create() {
		local cpus
		local mem
		local user
		local uid
		local gid

		# Set the default `krun` VM configuration. Do not overwrite existing
		# user configuration if the file already exists.
		if [ ! -f "$(krun_vmconfig)" ]; then
			cpus="$(grep -c '^processor[[:space:]]*:' /proc/cpuinfo)"
			mem="$(awk '/^MemTotal:/ {printf "%d", $2/1024}' /proc/meminfo)"
			cat <<CONFIG >"$(krun_vmconfig)"
{
	"cpus": $((cpus <= 32 ? (cpus + 1) / 2 : 16)),
	"ram_mib": $(((mem + 1) / 2))
}
CONFIG
		fi

		# We need to use `SIGKILL` for stopping `krun` containers, because
		# of a limitation of the runtime.
		podman create \
			--runtime=krun \
			--name="$name" \
			--hostname="$name" \
			--publish="127.0.0.1:$port:22" \
			--stop-signal=SIGKILL \
			"$image" \
			>/dev/null
		podman cp "$(ssh_id).pub" "$name:/etc/ssh/authorized_keys"

		# Provision the our user on the devbox. The `krun` runtime does not
		# support `podman exec` so execute the provisioning script over SSH.
		engine_start
		ssh_configure
		engine_waitforsshd
		user="$(id -un)"
		uid="$(id -u)"
		gid="$(id -g)"
		ssh -q -F "$(ssh_config)" "root@$name" "
			set -eu
			if ! getent group '$gid' >/dev/null; then
				groupadd -g '$gid' '$user'
			fi
			useradd -g '$gid' -m -s '\$(command -v bash)' -u '$uid' '$user'
		"
		engine_stop
	}

	engine_start() {
		# As a security precaution, do not allow image-provided `krun`
		# configurations, and write one from the host. This greatly reduces
		# the possible attack surface from the devbox, as it does not allow
		# an attacker to control VM startup options (e.g. a custom kernel).
		podman cp "$(krun_vmconfig)" "$name:/.krun_vm.json"
		podman start "$name" >/dev/null
	}

	engine_waitforsshd() {
		for _ in {1..10}; do
			if ssh -q -F "$(ssh_config)" "root@$name" true; then
				return 0
			fi
			sleep 0.1 2>/dev/null || sleep 1
		done
		general_error "devbox SSH server did not become ready"
	}

	engine_stop() {
		podman stop "$name" >/dev/null
	}

	engine_iscreated() {
		podman inspect "$name" &>/dev/null
	}

	engine_isrunning() {
		local running

		running="$(podman inspect --format="{{.State.Running}}" "$name")"
		[ "$running" = "true" ]
	}

	engine_hostname() {
		printf "127.0.0.1\n"
	}

	engine_port() {
		local mapping

		mapping="$(podman port "$name" 22/tcp | head -n1)"
		parse_port "${mapping##*:}"
	}
else
	general_error "no container engine installed"
fi

main() {
	parse_opts "$@"
	engine_init
	"cmd_$command" ${args[@]+"${args[@]}"}
}

main "$@"
