#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

C="dbx"

if ! container system status &>/dev/null; then
	container system start >/dev/null
fi

container start $C >/dev/null
