#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

c="dbx"
d="$HOME/Developer"

workdir="$(realpath "$PWD")"
if [[ "$workdir" != "$d"* ]]; then
    workdir="$d"
fi

podman start "$c" >/dev/null
exec podman exec \
    --detach-keys "" \
    --interactive \
    --tty \
    --user "$(id -u)" \
    --workdir "$workdir" \
    "$c" \
    fish --login
