#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 Nicholas Rodrigues Lordello <n@lordello.net>

set -euo pipefail

root="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
machine="${DBX_MACHINE:-dbx}"

if ! container system status &>/dev/null; then
	container system start >/dev/null
fi

container machine run --name="$machine" true >/dev/null

# The IP address assigned to the machine changes on restarts, so update the SSH
# configuration with the current value.
ip="$(container machine inspect "$machine" | jq -r '.[0].ipAddress')"
cat "$root/ssh/config.in" \
	| sed -e 's|$ROOT|'"$root"'|g' \
	| sed -e 's|$MACHINE|'"$machine"'|g' \
	| sed -e 's|$IP|'"$ip"'|g' \
	>"$root/ssh/$machine.config"
