#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

C="dbx"

if ! container system status &>/dev/null; then
	container system start
fi

if container list --all | grep $C >/dev/null; then
	echo "already created"
	exit
fi

container create \
	--cpus 4 \
	--memory 8G \
	--name $C \
	--publish 127.0.0.1:4222:22 \
	$C
