#!/usr/bin/env bash
# SPDX-License-Identifier: 0BSD

set -euo pipefail

r="$HOME/.dbx"
c="dbx"
d="$HOME/Developer/dbxroot"

if podman container exists "$c"; then
    echo "already created"
    exit
fi

podman create \
    --hostname dbx \
    --label manager=dbx \
    --name "$c" \
    --user root:root \
    --userns keep-id \
    --volume "$d:$d:z" \
    --volume "$r/dbx-init:/usr/local/bin/dbx-init:ro,z" \
    registry.fedoraproject.org/fedora-toolbox:43 \
    dbx-init "$(id -u)" "$(id -g)"
