#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

r="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
c="dbx"
d="$HOME/Developer"

if podman container exists "$c"; then
    echo "already created"
    exit
fi

podman create \
    --hostname dbx \
    --label manager=dbx \
    --name "$c" \
    --user root:root \
    --userns keep-id \
    --volume "$d:$d:z" \
    --volume "$r/dbx-init:/usr/local/bin/dbx-init:ro,z" \
    registry.fedoraproject.org/fedora-toolbox:43 \
    dbx-init "$(id -u)" "$(id -g)"
podman start "$c" >/dev/null
